### ISSUE TITLE
Viewcat - problem with "convertorderby"

### ISSUE THREAD

**Issue by chaoos2** [XoopsModules25x/wfdownloads#21]
When I go through a category, system error dump me:

Error : Error: Call to undefined function convertorderbytrans()

Unless the file viewcat.php remove these lines, it works:

        $orderbyTrans = convertorderbytrans($orderby);
        $xoopsTpl->assign('orderby', convertorderbyout($orderby));
        $xoopsTpl->assign('lang_cursortedby', sprintf(_MD_WFDOWNLOADS_CURSORTBY, convertorderbytrans($orderby)));
        $orderby = convertorderbyout($orderby);

What could be the problem? I have PHP 7.1 (but it happens even in version 5.6), MariaDB 5.5, web in English.

**Comment by mambax7** [comment]
That should be solved, so I'm closing it
