### ISSUE TITLE
Media file preview

### ISSUE THREAD

**Issue by chaoos2** [XoopsModules25x/wfdownloads#23]
When a media file (image or video), does not display a preview in singlefile.tpl.

**Comment by cesagonchu** [comment]
It will be easier to fix the bugs if you specify your configuration and the errors displayed by the debug mode of xoops.

**Comment by chaoos2** [comment]
I have XOOPS 2.5.9 beta1, PHP 7.1.1, MySQL 5.5.5-10.1.21-MariaDB, wfdownloads 3.23 rc5.
Errors when debugging are not reported. According to the code module is to automatically display a preview when it comes, for example, the image. I think you just need to add some missing code, which refers to the type of file to download.

**Comment by mambax7** [comment]
It seems to be working fine in my latest version: https://github.com/mambax7/wfdownloads
