### ISSUE TITLE
Feedback after testing Wfdownloads 3.3

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#24]
Hi Team :)
I am new here and i'm very glad to contribute with you by giving feedback regarding issues encountred when testing Xoops modules. By the way i am using Xoops since 2013 and i was happy to joing the community of Xoops users.
I tested Wfdownloads 3.3 and i founded some issues which i'd like to share with you here : 
1. All pages generated by the module have as title the name of the module (wfdownloads) instead of having the title of each download.
2. There is an error with the link of modifying files in singlefile page (<{$down.adminlink}>) : "/modules/wfdownloads//admin/downloads.php?op=download.edit&lid=".
There is two slashes between "wfdownloads" and "admin".
3. Page "ratings.php" is unvailable due to these errors : 
- Undefined offset: 2436 in file /modules/wfdownloads/admin/ratings.php ligne 73
- Error: Call to a member function getVar() on null dans le fichier /modules/wfdownloads/admin/ratings.php ligne 73
4. Some errors in page "downloads.php" : 
- Undefined variable: imagearray dans le fichier /modules/wfdownloads/admin/downloads.php ligne 205
- Error: Call to a member function getVar() on integer dans le fichier /modules/wfdownloads/admin/downloads.php ligne 232
5. Page "permissions.php" : After changing the permissions, the changes are not made and i am redirected to the home page (index.php).

Here is my environment : XOOPS 2.5.10 / PHP | 7.2.33 / Mysql 5.5-10.1.46-MariaDB-cll-lve
Please excuse my english and if there something not clear, feel free to let me know that.

**Comment by mambax7** [comment]
Thank you for your report. We'll be looking into it soon...

**Comment by mambax7** [comment]
Please take a look at the 3.30 Beta 3 and let me know if it's better:
https://github.com/mambax7/wfdownloads/releases/tag/3.30_Beta-3

I didn't have time to do any big testing, so bugs are still possible...

**Comment by Aminov81** [comment]
The issue n°1 is stille here. All pages generated by the module have as title the name of the module (wfdownloads) instead of having the title of each download.

**Comment by Aminov81** [comment]
Page "ratings.php" is still inaccessible unvailable due to these errors :
- Undefined offset: 2436 in the file /modules/wfdownloads/admin/ratings.php line 78
- Error: Call to a member function getVar() on null in the file /modules/wfdownloads/admin/ratings.php line 78

**Comment by Aminov81** [comment]
Page "permissions.php" : After changing the permissions, the changes are not made and i am redirected to the home page.

**Comment by Aminov81** [comment]
You can close this one too now..
