### ISSUE TITLE
Code injected

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#25]
Hey Everyone :)
I noticed by accident that in the end of the files "singlefile" and "viewcat" there is a strange java script injected in the end of those files after closing the php code. This script is peretty strange for me (i am not developper) because it does nothing to have normally with Wfdownloads, and when i edit the page code source of my wfdonloads pages i see this script out of the html tag !!
Here is the code : 
`<script type="text/javascript">

    $('.magnific_zoom').magnificPopup({
        type: 'image',
        image: {
            cursor: 'mfp-zoom-out-cur',
            titleSrc: "title",
            verticalFit: true,
            tError: 'The image could not be loaded.' // Error message
        },
        iframe: {
            patterns: {
                youtube: {
                    index: 'youtube.com/',
                    id: 'v=',
                    src: '//www.youtube.com/embed/%id%?autoplay=1'
                }, vimeo: {
                    index: 'vimeo.com/',
                    id: '/',
                    src: '//player.vimeo.com/video/%id%?autoplay=1'
                }, gmaps: {
                    index: '//maps.google.',
                    src: '%id%&output=embed'
                }
            }
        },
        preloader: true,
        showCloseBtn: true,
        closeBtnInside: false,
        closeOnContentClick: true,
        closeOnBgClick: true,
        enableEscapeKey: true,
        modal: false,
        alignTop: false,
        mainClass: 'mfp-img-mobile mfp-fade',
        zoom: {
            enabled: true,
            duration: 300,
            easing: 'ease-in-out'
        },
        removalDelay: 200
    });
</script>`

Is this script put intentionnaly by the developpers or is someone placed there by error ?

**Comment by mambax7** [comment]
It's from/for the Magnific-Popup
https://github.com/dimsemenov/Magnific-Popup

**Comment by Aminov81** [comment]
Ok, thank you for your feedback dear mamba :-)

**Comment by Aminov81** [comment]
Ok, Thank you for your feedback dear Michael :-)
