### ISSUE TITLE
WFdownloads 3.3 - Brokenfile

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#30]
"Brokenfile.php" is inaccessible due to this error :
Class 'XoopsUserUtility' not found in the file /modules/wfdownloads/brokenfile.php, line 200

**Comment by mambax7** [comment]
In /header.php add in line 34:
```php
xoops_load('XoopsUserUtility');
```

See: https://github.com/mambax7/wfdownloads/blob/master/header.php

**Comment by Aminov81** [comment]
Now it works fine.
You can close this issue :)
