### ISSUE TITLE
Wfdownloads 3.3 - ratings.php

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#32]
The page "ratings.php" is inaccessible due to these errors :
- Undefined offset: 2436 in file /modules/wfdownloads/admin/ratings.php, line 78
- Error: Call to a member function getVar() on null in file /modules/wfdownloads/admin/ratings.php, line 78

**Comment by mambax7** [comment]
Can you check your download item # 2436 ? It seems to me that the Rating table (wfdownloads_votedata) has a rating information about a download #2436 that doesn't exist anymore

Check on: modules/wfdownloads/admin/downloads.php?op=download.add&lid=2436

**Comment by mambax7** [comment]
I've changed that to show you an error (in https://github.com/XoopsModules25x/wfdownloads/pull/27/commits/2b6500d94257d87081177209233e65bd8a579f39):
![image](https://user-images.githubusercontent.com/613686/101396224-fe71fe00-3898-11eb-8ed9-03c5058a6317.png)

**Comment by Aminov81** [comment]
Yes exactly, i had deleted this download directly from the data base (using phpmyadmin). That's perhaps why the votedata remained in database (the vote data related to this download wasn't deleted too).

**Comment by Aminov81** [comment]
Sorry, where i can download the new ratings file ?

**Comment by mambax7** [comment]
https://github.com/mambax7/wfdownloads

**Comment by mambax7** [comment]
The file itself is here: https://github.com/mambax7/wfdownloads/blob/master/admin/ratings.php

**Comment by Aminov81** [comment]
Perfect, problem solved :+1:
