### ISSUE TITLE
WFdownloads - Admin links

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#34]
There is two slashes between "wfdownloads" and "admin" in the admin links of singlefile page (<{$down.adminlink}>) . 
Examples : 
/modules/wfdownloads//admin/downloads.php?op=download.edit&lid=
/modules/wfdownloads//admin/downloads.php?op=download.delete&lid=

**Comment by mambax7** [comment]
Cannot reproduce it here. What theme are you using?

**Comment by Aminov81** [comment]
An old theme of xoops which i had adapted to my needs.
Never mind i fixed this directely in the template singlefile.tpl
You can close this, and thank you for your patience.
