### ISSUE TITLE
WFdownloads 3.3 - permissions.php

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#35]
After changing the permissions and validating i am redirected to the home page of the website, but the changes are not made.

**Comment by mambax7** [comment]
Changing permissions on what and for whom? 
- access or upload permissions, or both? 
- permissions for Webmaster, Registered User, or Anonymous, or all? 

It works fine on my installation for all of the above!

**Comment by Aminov81** [comment]
Sorry for not being precise. 
I mean permissions for all (Webmaster, Registered User, or Anonymous) including the other groups i had created. Impossible to change the permissions of any group.
I only see permissions for accessing the categories, i don't see any upload permissions !

**Comment by mambax7** [comment]
The problem is that we have different data in the database, so sometimes it's hard for me to test it. 
Zip the wfDownload tables and email them to me, so I can use the same data and the same table structure, as you do.

**Comment by Aminov81** [comment]
Of course, what is you email adress ?

**Comment by mambax7** [comment]
mambax7 @ gmail.com

**Comment by Aminov81** [comment]
I'll do it tomorrow.
It's late now on the other side of the atlantic ;-)

**Comment by Aminov81** [comment]
The issue is now solved after i deleted the categories which had names with arabic alphabet. I deleted some groups of users too. I don't know the relationship but it seems that it fixed the problem !
It works fine now both for access and upload.
You can close this too.

**Comment by mambax7** [comment]
In the new installation with the testdata, can you enter categories in Arabic? We have to make sure that it works!

**Comment by Aminov81** [comment]
Yes i can enter categories in Arabic but i can't modify the access permissions through permissions page. I had to make it directly by editing the category.
The problem concerns only access permissions not download permissions.
That's weird !
