### ISSUE TITLE
WFdownloads 3.3 - mimetypes.php

### ISSUE THREAD

**Issue by Aminov81** [XoopsModules25x/wfdownloads#36]
- Undefined variable: buttonTray in the file /modules/wfdownloads/admin/mimetypes.php line 84
- The extensions .doc and .docx are not supported.

**Comment by mambax7** [comment]
Should be fixed in:
- https://github.com/XoopsModules25x/wfdownloads/pull/27/commits/a50c0779c77f6c9eb38a662e71067cf9ce93e570
- https://github.com/XoopsModules25x/wfdownloads/pull/27/commits/72f90e0e28af44cfae7fc3d0519cd21d7c4000c1

**Comment by Aminov81** [comment]
Please what files were modified here ?

**Comment by Aminov81** [comment]
docx format is still not supported..
